config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }
  devise_scope :user do
    put 'api/v1/users/:id', to: 'registrations#update'
  end
  get 'dashboard', to: 'dashboard#index'
  root to: 'dashboard#index'

  namespace :api do
    namespace :v1 do
      resources :content_entities, path: 'contentEntities' do
        get :inbox, on: :collection
      end
      resources :links, only: [:index, :show]
      resources :notes, only: :index
      resources :tags, only: [:index, :show]
      resources :users
      resources :groups do
        member do
          get :other_users
          get :members
        end
      end
      resources :comments
    end
  end

  devise_for :administrators do
    get '/administrators/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    resources :administrators
    root to: 'dashboard#index'
  end

  resources :users, only: [:edit, :update]
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  ## VALIDATIONS
  validates :first_name, :last_name, :email,
            presence: true

  def to_s
    "#{full_name} (#{email})"
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < Admin::BaseController
  inherit_resources
  defaults route_prefix: 'admin'

  def index
    @q = Administrator.search(params[:q])
    @q.sorts = 'last_name ASC' if @q.sorts.blank?
    @administrators = @q.result(distinct: true).page(params[:page])
  end

  def show
    @administrator = Administrator.find(params[:id].to_i)
    @password = session.delete(:admin_password)
  end

  def create
    password = Devise.friendly_token.first(8)
    @administrator = Administrator.new(resource_params.merge(password: password))
    if @administrator.save
      session[:admin_password] = password
      redirect_to [:admin, @administrator]
    else
      render action: :new
    end
  end

  def update
    @administrator = Administrator.find(params[:id])
    if @administrator.update_attributes(resource_params)
      redirect_to [:admin, @administrator]
    else
      render action: :edit
    end
  end

  private

  def resource_params
    if p = params[resource_instance_name].presence
      p.permit(:email, :first_name, :last_name)
    else
      {}
    end
  end
end

app/views/admin/administrators/_form.html.haml
.box
  .box-header
    %span.title
      - if resource.persisted?
        = resource.to_s
      - else
        = t('common.new_record', default: 'New record')
    = render partial: "/admin/shared/toolbar", locals: {resource: resource}
  .box-content
    = simple_form_for [:admin, resource], html: { class: "form-horizontal" } do |f|
      .padded
        = f.input :first_name, input_html: { class: "validate[required]" }
        = f.input :last_name, input_html: { class: "validate[required]" }
        = f.input :email, input_html: { class: "validate[required]" }
      .form-actions
        %button.btn.btn-blue.btn-default{type: "submit"}
          = t('common.save', default: "Save")

app/views/admin/administrators/edit.html.haml
- content_for(:header_title) do
  = t('common.editing', default: 'Editing:')
  = resource.to_s

= render 'form'

app/views/admin/administrators/index.html.haml
.box
  .box-header
    %span.title= t('admin.administrators.index.header', default: 'Admins')
    %ul.box-toolbar
      %li
        = link_to 'New administrator', new_admin_administrator_path

  .box-content
    %table.table.table-normal
      %thead
        %tr
          %th
            = sort_link @q, :last_name, t('admin.administrators.index.table.name', default: 'Name')
          %th(width="40px")
            - #= t('common.actions', default: 'Actions')
      %tbody
        - @administrators.each do |administrator|
          %tr
            %td= link_to administrator, [:admin, administrator]
            %td
              .btn-group
                %button.btn.btn-default.dropdown-toggle.btn-xs(data-toggle="dropdown")
                  %i{ class: "fa fa-cog" }
                %ul.dropdown-menu.pull-right
                  %li
                    = link_to [:edit, :admin, administrator] do
                      %i{ class: "fa fa-edit" }
                      = t('common.edit', default: 'Edit')
                  %li
                    = link_to  [:admin, administrator], method: :delete, data: { confirm: t('common.are_you_sure', default: "Are you sure?") } do
                      %i{ class: "fa fa-trash" }
                      = t('common.delete', default: 'Delete')
  .table-footer
    = paginate @administrators

app/views/admin/administrators/new.html.haml
- content_for(:header_title) do
  = t('admin.administrators.new_admin', default: 'New administrator')

= render 'form'

app/views/admin/administrators/show.html.haml
- content_for(:header_title) do
  = resource.to_s
.box
  .box-header
    %span.title= resource.to_s
    = render partial: "/admin/shared/toolbar", locals: {resource: resource}
  .box-content
    %table.table.table-striped.responsive
      %tbody
        %tr
          %td(width="15%")
            = resource.class.human_attribute_name(:first_name)
          %td= resource.first_name
        %tr
          %td(width="15%")
            = resource.class.human_attribute_name(:last_name)
          %td= resource.last_name
        %tr
          %td(width="15%")
            = resource.class.human_attribute_name(:email)
          %td= resource.email
        - if @password.present?
          %tr
            %td(width="15%")
              = resource.class.human_attribute_name(:password)
            %td= @password
            %br/
            %em
              %strong
                = succeed ":" do
                  = draw_icon 'warning-sign'
                  = t('common.warning', default: 'Warning')
              = t('admin.administrators.show.password_will_not_be_show_again')
        %tr
          %td(width="15%")
            = resource.class.human_attribute_name(:current_sign_in_at)
          %td= resource.current_sign_in_at
        %tr
          %td(width="15%")
            = resource.class.human_attribute_name(:current_sign_in_ip)
          %td= resource.current_sign_in_ip
        %tr
          %td(width="15%")
            = resource.class.human_attribute_name(:last_sign_in_at)
          %td= resource.last_sign_in_at
        %tr
          %td(width="15%")
            = resource.class.human_attribute_name(:last_sign_in_ip)
          %td= resource.last_sign_in_ip