config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }
  devise_scope :user do
    put 'api/v1/users/:id', to: 'registrations#update'
  end
  get 'dashboard', to: 'dashboard#index'
  root to: 'dashboard#index'

  namespace :api do
    namespace :v1 do
      resources :content_entities, path: 'contentEntities' do
        get :inbox, on: :collection
      end
      resources :links, only: [:index, :show]
      resources :notes, only: :index
      resources :tags, only: [:index, :show]
      resources :users
      resources :groups do
        member do
          get :other_users
          get :members
        end
      end
      resources :comments
    end
  end

  devise_for :administrators do
    get '/administrators/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    resources :administrators
    root to: 'dashboard#index'
  end

  resources :users, only: [:edit, :update]
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_reader :user_tokens

  belongs_to :owner, class_name: 'User'
  has_many :content_entities
  has_and_belongs_to_many :users, join_table: :participants

  validates :name, presence: true
  validates :owner, presence: true
  validates :icon, presence: true
  validates :name, uniqueness: true

  after_destroy do
    content_entities.update_all(inbox: true, group_id: nil)
  end

  def other_users(query)
    User.filtering(query).not_members(user_ids)
  end

  def self.visible_for(user)
    user.groups
  end
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApplicationController
  load_and_authorize_resource
  respond_to :json

  def index
    respond_with @groups
  end

  def create
    attrs = {
      name: params[:group][:name],
      icon: params[:group][:icon],
      owner_id: current_user.try(:id)
    }
    group = Group.new(attrs)
    group.users << current_user if group.save
    respond_with :api, :v1, group
  end

  def update
    @group.icon = params[:group][:icon] if params[:group][:icon]
    @group.name = params[:group][:name]
    if ids = params[:group][:userIds]
      @group.user_ids = ids.push(@group.owner_id).uniq
    end
    @group.save

    respond_with :api, :v1, @group
  end

  def other_users
    respond_with @group.other_users(params[:q]), root: false
  end

  def members
    respond_with @group.users.map { |u| { id: u.id, email: u.email }}, root: false
  end

  def show
    respond_with @group
  end

  def destroy
    respond_with @group.destroy
  end

  private

  def group_params
    params.require(:group).permit(group: [:name, :icon])
  end
end

app/views/groups/_form.html.haml
= simple_form_for @group, html: { class: '', role: 'form'} do |f|
  %fieldset
    = f.label 'Name'
    = f.input_field :name, class: 'form-control input-sm'
    %br
    .form-actions
      = f.button :submit, class: 'btn btn-success'

app/views/groups/edit.html.haml
.row
  .col-sm-6
    .panel.panel-default
      .panel-heading
        %h4 Edit
      .panel-body
        = render 'form'

app/views/groups/index.html.haml
.panel.panel-default
  .panel-heading
    %a.pull-right{:href => "#"} View all??????????
    %h4 Groups
    = link_to "New group", new_group_path, class: "button btn btn-lg btn-success"
  .panel-body
    - if @groups
      Group list:
      - @groups.each do |group|
        .list-group-item
          = group.name
          = link_to 'Show', group_path(group), class: 'btn btn-info'
          - if can? :destroy, group
            = link_to 'Delete', group_path(group), method: :delete, class: 'btn btn-danger pull-right'
          - if can? :update, group
            = link_to 'Update', edit_group_path(group), class: 'btn btn-warning pull-right'
    - else
      nie należysz do żadnej grupy

app/views/groups/new.html.haml
.row
  .col-sm-6
    .panel.panel-default
      .panel-heading
        %h4 New group
      .panel-body
        = render 'form'

app/views/groups/show.html.haml
.row
  .col-sm-6
    .panel.panel-default
      .panel-heading
        %h4= "Name: #{@group.name}"
      .panel-body
        %p
          Participants:
          %ul
            - @group.users.each do |user|
              %li
                = user.email
        .clearfix
        %hr/
        Owner:
        = @group.owner.email
  - if can? :update_users, @group
    .col-sm-6
      .well
        %h4 Add new member
        .form-group
          = simple_form_for @group, url: update_users_group_path, method: 'post' do |f|
            = f.input_field :user_tokens, label: false, input_html: { data: { pre: @preload_users, url: other_users_group_path(@group) } }, label: false, class: 'form-control input-sm'
            %br
            = f.submit 'Apply changes', class: 'btn btn-success'

= link_to 'Back', groups_path, class: 'btn btn-default'