config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }
  devise_scope :user do
    put 'api/v1/users/:id', to: 'registrations#update'
  end
  get 'dashboard', to: 'dashboard#index'
  root to: 'dashboard#index'

  namespace :api do
    namespace :v1 do
      resources :content_entities, path: 'contentEntities' do
        get :inbox, on: :collection
      end
      resources :links, only: [:index, :show]
      resources :notes, only: :index
      resources :tags, only: [:index, :show]
      resources :users
      resources :groups do
        member do
          get :other_users
          get :members
        end
      end
      resources :comments
    end
  end

  devise_for :administrators do
    get '/administrators/sign_out' => 'devise/sessions#destroy'
  end
  namespace :admin do
    resources :administrators
    root to: 'dashboard#index'
  end

  resources :users, only: [:edit, :update]
end

app/views/layouts/_admin_panel.html.haml
/ Navigation
%nav.navbar.navbar-default.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar

    = link_to 'EnlightenmentApp', root_path, class: 'a navbar-brand'
  / /.navbar-header
  %ul.nav.navbar-top-links.navbar-right
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        %i.fa.fa-user.fa-fw
        %i.fa.fa-caret-down
      %ul.dropdown-menu.dropdown-user
        %li
          = link_to '<i class="fa fa-sign-out fa-fw"></i> Logout'.html_safe, destroy_administrator_session_path, method: 'delete'

  .navbar-default.sidebar{:role => "navigation"}
    .sidebar-nav.navbar-collapse
      %ul#side-menu.nav
        %li.sidebar-search
          .input-group.custom-search-form
            %input.form-control{:placeholder => "Search...", :type => "text"}/
            %span.input-group-btn
              %button.btn.btn-default{:type => "button"}
                %i.fa.fa-search
          / /input-group
        %li
          = link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe, admin_root_path
        %li
          = link_to '<i class="fa fa-user fa-fw"></i> Administrators'.html_safe, admin_administrators_path
        %li
          %a{:href => "#"}
            %i.fa.fa-bar-chart-o.fa-fw
            Charts

        %li
          %a{:href => "tables.html"}
            %i.fa.fa-table.fa-fw
            Tables

app/views/layouts/_panels.html.haml
.page-container
  / top navbar
  %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
    .navbar-header
      %button.navbar-toggle{"data-target" => ".sidebar-nav", "data-toggle" => "offcanvas", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Bootstrap Hol
  .container-fluid
    .row.row-offcanvas.row-offcanvas-left
      / sidebar
      #sidebar.col-xs-6.col-sm-3.sidebar-offcanvas{:role => "navigation"}
        %div{"data-offset-bottom" => "90", "data-offset-top" => "45", "data-spy" => "affix"}
          %ul#sidebar-nav.nav
            %li
              %a{:href => "#"} Home
            %li
              %a{:href => "#section1"} Section 1
            %li
              %a{:href => "#section2"} Section 2
            %li
              %a{:href => "#section3"} Section 3
            %li
              %a{:href => "#"} Holo Theme
      / /sidebar
      / /main
      .col-xs-12.col-sm-9{"data-spy" => "scroll", "data-target" => "#sidebar-nav"}
        .row

app/views/layouts/admin.html.haml
!!!
%html
  %body
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title SB Admin 2 - Bootstrap Admin Theme
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    = stylesheet_link_tag 'sb-admin/admin', media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "sb-admin/admin", "data-turbolinks-track" => true
    = csrf_meta_tags
    #wrapper
      = render 'layouts/admin_panel'
    #page-wrapper
      .row
        .col-lg-12
          = yield
 

app/views/layouts/admin_auth.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    / Bootstrap Core CSS
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
    %title Panel Admin
    = stylesheet_link_tag 'sb-admin/admin', media: "all", "data-turbolinks-track" => true
    %link{href: "http://getbootstrap.com/dist/css/bootstrap.min.css", rel: "stylesheet"}
    %link{href: "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", rel: "stylesheet"}
    = javascript_include_tag "sb-admin/admin", "data-turbolinks-track" => true
    %script{src: "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"}
    = csrf_meta_tags
  %body
    .container
      .row
        .col-md-4.col-md-offset-4
          = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title EnlightenmentApp
    = stylesheet_link_tag 'holo/holo', media: 'all'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    %script{src: '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'}
    = csrf_meta_tags
  %body

app/views/layouts/layout.erb
<!doctype html>
<html>
<head>

  <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800">


  <meta charset="utf-8">

  <!-- Always force latest IE rendering engine or request Chrome Frame -->
  <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">

  <!-- Use title if it's in the page YAML frontmatter -->
  <title><%= data.page.title || "Core Admin Theme" %></title>

  <%= stylesheet_link_tag "application" %>

  <!--[if lt IE 9]>
  <%= javascript_include_tag "vendor/html5shiv" %>
  <%= javascript_include_tag "vendor/excanvas" %>
  <![endif]-->

  <%= javascript_include_tag  "application" %>
</head>



<body>
<%= partial 'layouts/top_navigation' %>
<%= partial 'layouts/side_navigation' %>

<div class="main-content">
  <div class="container">
    <div class="row">

      <div class="area-top clearfix">
        <div class="pull-left header">
          <h3 class="title">
            <i class="<%= crumbs[:secondary][:icon] %>"></i>
            <%= crumbs[:secondary][:label] %>
          </h3>
          <h5>
            A subtitle can be added here
          </h5>
        </div>

        <ul class="list-inline pull-right sparkline-box">

          <li class="sparkline-row">
            <h4 class="blue"><span>Orders</span> 847</h4>
            <div class="sparkline big" data-color="blue"><!--<%= random_numbers(12).join(",") %>--></div>
          </li>

          <li class="sparkline-row">
            <h4 class="green"><span>Reviews</span> 223</h4>
            <div class="sparkline big" data-color="green"><!--<%= random_numbers(12).join(",") %>--></div>
          </li>

          <li class="sparkline-row">
            <h4 class="red"><span>New visits</span> 7930</h4>
            <div class="sparkline big"><!--<%= random_numbers(12).join(",") %>--></div>
          </li>

        </ul>
      </div>
    </div>
  </div>

  <div class="container padded">
    <div class="row">

      <!-- Breadcrumb line -->

      <div id="breadcrumbs">
        <div class="breadcrumb-button blue">
          <span class="breadcrumb-label"><i class="icon-home"></i> Home</span>
          <span class="breadcrumb-arrow"><span></span></span>
        </div>

        <% if link_level == 2 %>
            <div class="breadcrumb-button">
              <span class="breadcrumb-label">
                <i class="<%= crumbs[:primary][:icon] %>"></i> <%= crumbs[:primary][:label] %>
              </span>
              <span class="breadcrumb-arrow"><span></span></span>
            </div>
        <% end %>

        <div class="breadcrumb-button">
          <span class="breadcrumb-label">
            <i class="<%= crumbs[:secondary][:icon] %>"></i> <%= crumbs[:secondary][:label] %>
          </span>
          <span class="breadcrumb-arrow"><span></span></span>
        </div>
      </div>
    </div>
  </div>

  <div class="container padded">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/layouts/only_topbar.html.haml
<!doctype html>
%html
  %head
    %meta{content: "width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0", name: "viewport"}/
    %link{href: "https://fonts.googleapis.com/css?family=Open+Sans:400,600,800", rel: "stylesheet"}/
    %meta{charset: "utf-8"}/
    / Always force latest IE rendering engine or request Chrome Frame
    %meta{content: "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    / Use title if it's in the page YAML frontmatter
    %title= data.page.title || "Core Admin Theme"
    = stylesheet_link_tag "application"
    = javascript_include_tag  "application"
  %body
    = partial "layouts/top_navigation"
    .container
      = yield